-- BUAT DATABASE
CREATE DATABASE IF NOT EXISTS db_topup;
USE db_topup;

-- TABEL USER (ADMIN & USER)
DROP TABLE IF EXISTS users;
CREATE TABLE users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    no_hp VARCHAR(20) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    role ENUM('user','admin') NOT NULL DEFAULT 'user'
);


-- DATA ADMIN & USER (NOMOR HP dan PASSWORD JANGAN LUPA!)naufal123,admin123
INSERT INTO users (no_hp, password, role) VALUES
('089876543210', '$2y$10$FFvqNn3qGXY2EVingJg4KeNZlYG8WLu.BinllIP3bxyTRCj2YRxlS', 'admin'),
('081234567890', '$2y$10$eeS3zlHYG/J5RoV79KgeJ.H4eROPi7yNBnon2.xt1XWHeUdzZbH9y', 'user');

-- TABEL PRODUK (HANYA ISI YANG VALID)
DROP TABLE IF EXISTS produk;
CREATE TABLE produk (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nama VARCHAR(255) NOT NULL,
    harga INT NOT NULL
);

-- DATA PRODUK SESUAI PILIHAN DI WEB
INSERT INTO produk (nama, harga) VALUES
('475 Points', 55293),
('2050 Points', 221168),
('3650 Points', 384081),
('5350 Points', 551931),
('11000 Points', 1085102);

DROP TABLE IF EXISTS pesanan;
CREATE TABLE pesanan (
    id INT AUTO_INCREMENT PRIMARY KEY,
    user_id INT NOT NULL,
    riot_id VARCHAR(100) NOT NULL,
    produk_id INT NOT NULL,
    tgl_pesan TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id),
    FOREIGN KEY (produk_id) REFERENCES produk(id)
);


CREATE TABLE IF NOT EXISTS pertanyaan (
    id INT AUTO_INCREMENT PRIMARY KEY,
    individu VARCHAR(20) NOT NULL,
    tipe VARCHAR(20) NOT NULL,
    nama VARCHAR(100) NOT NULL,
    whatsapp VARCHAR(20) NOT NULL,
    deskripsi TEXT NOT NULL,
    tgl_kirim TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
